### ISSUE TITLE
Child.attributes not found when child node is evaluated to null due to conditional rendering with && operator

### ISSUE THREAD

**Issue by aalises** [k1r0s/preact-bind-group#11]
Hello!

- using Preact 8 and latest Chrome Version

When rendering conditionally an element inside the BindGroup component with the && operator, when the condition is evaluated to false (hence the element is not rendered), the library crashes at the Child.attributes check performed on the mapChildren function as the child parameter is null (the expression is evaluated to falsy when the rendering condition is not met and is taken by the library as a null node).

Example of crash:
```
const renderCondition = false;
...

<BindGroup watch={change => {this.handleFormChange(change); } } preload={this.state.form}>
    //Creates a "null" child node which causes the library to crash
    {renderCondition &&  <input  data-bind="username" maxlength="5" />}
</BindGroup>
``` 
Crashes on the first **if** statement:
```
   static mapChildren (child, cbk, state, setState) {
//child.attributes is not found as child is null!
    if (child.attributes instanceof Object && child.attributes[FormGroup.bindAttrName]) {
      child.attributes = {
        ...child.attributes,
        [child.attributes[FormGroup.bindAttrEvent] || 'onChange']: evt => cbk.apply(null, [...FormGroup.createChangeReport(child, evt, setState), evt]),
        name: child.attributes[FormGroup.bindAttrName],
        ...FormGroup.getFormProps(child, state)
      }
    } else if (child.children instanceof Array && child.children.length) {
      child.children = child.children.map(child => FormGroup.mapChildren(child, cbk, state, setState));
    }
    return child;
  }
}

```
A possible solution would be to add a null check at the start of the function, e.g

```
 static mapChildren (child, cbk, state, setState) {
    if(!child) return; //Possible fix
    if (child.attributes instanceof Object && child.attributes[FormGroup.bindAttrName]) {
      child.attributes = {
        ...child.attributes,
```

WDYT?

**Comment by k1r0s** [comment]
Hi @aalises 

> A possible solution would be to add a null check at the start of the function, e.g

wut problem is this function `mapChildren` is being used as a map predicate, so it should return a node or null.

Would you make a PR ? :D
