### ISSUE TITLE
Changes are only triggered onBlur

### ISSUE THREAD

**Issue by alexjoverm** [k1r0s/preact-bind-group#2]
Reproduce:

 - Just go to the demo https://codesandbox.io/s/wmpv1o4z8
 - Change an input, you'll see that it only triggers the watch callback when blurs. It doesn't matter if you change the `data-event` attribute

**Comment by k1r0s** [comment]
wut..

its working as expected for me: changes are only triggered `onChange` by default. 

but if you add `<input data-bind="value0" data-event="onInput"/>` then that input would trigger changes anytime when typing

do you think this is a bug?

**Comment by k1r0s** [comment]
https://codesandbox.io/s/mjxnqj5o2y

**Comment by alexjoverm** [comment]
Oh, the data-event should be placed on the `input` :D. Cool, let's specify that in the docs, otherwise it's kind of confusing.

Does the `onChange` event in Preact gets triggered when the input is blurred? In React, the `onChange` is equivalent to the `onInput` that you're saying.

**Comment by k1r0s** [comment]
Yes, seems like React and Preact aren't the same xd

**Comment by alexjoverm** [comment]
Sorry, this was a confusion from my side. I think it could be useful to add a note on the docs for the incoming React users. something like:

> Note: keep in mind that `onInput` in Preact === `onChange` in React, and `onChange` in Preact === `onBlur` on React

Closing...

**Comment by k1r0s** [comment]
Thanks bro! appreciated
