### ISSUE TITLE
Remove 2nd watch parameter

### ISSUE THREAD

**Issue by alexjoverm** [k1r0s/preact-bind-group#3]
I think that most of times it won't be needed, and if it is, it can be accessed by `Object.keys(obj)`.

What do you think?

**Comment by k1r0s** [comment]
mm, I added it coz its handy to read directly from arguments, if you don't need it, you don't have to declare it. But I guess is more clean to have it directly. 

Since `change` is an Object, some people will try to extract by other means and I guess isn't clean.

```
// you don't really need this
myUpdateChanger = (change, prop?) => ...

<BindGroup watch={myUpdateChanger}> 
...
</BindGroup>
```

```
// imo it helps to do things more naturaly
<BindGroup watch={(change, prop) => this.sideAction(prop) || this.myUpdateChanger(change)}> 
...
</BindGroup>
```
Does it answer your question?

**Comment by alexjoverm** [comment]
Yeah, that's a good statement, it makes sense.

Let's close it then, not forgetting to add to to the doc :) thanks!
